language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t vamsiveginati/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true vamsiveginati/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-latest"
  env: "Docker-latest-env"
  bucket_name: "elasticbeanstalk-us-east-1-677555219201"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_id: $AWS_SECRET_KEY